### ISSUE TITLE
nasc 0.8.0: Segmentation fault in Solus

### ISSUE THREAD

**Issue by algent-al** [parnold-x/nasc#188]
**Describe the bug**
nasc fails to run in Solus
```
$ com.github.parnold_x.nasc 
[INFO 10:42:47.652066] Application.vala:142: NaSC version: 0.8.0
[INFO 10:42:47.652091] Application.vala:145: Kernel version: 5.15.50-216.current
Segmentation fault (core dumped)

```
Here is the back-trace
```
(gdb) run
Starting program: /usr/bin/com.github.parnold_x.nasc 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
[INFO 10:46:00.999789] Application.vala:142: NaSC version: 0.8.0
[INFO 10:46:00.999825] Application.vala:145: Kernel version: 5.15.50-216.current
[New Thread 0x7fffdf031640 (LWP 2691)]
[New Thread 0x7fffde830640 (LWP 2692)]
[New Thread 0x7fffddcae640 (LWP 2693)]
[New Thread 0x7fffcffff640 (LWP 2694)]
[Thread 0x7fffcffff640 (LWP 2694) exited]
[New Thread 0x7fffcffff640 (LWP 2695)]
[New Thread 0x7fffcf7fe640 (LWP 2696)]
[Thread 0x7fffcffff640 (LWP 2695) exited]
[Thread 0x7fffcf7fe640 (LWP 2696) exited]
[New Thread 0x7fffcf7fe640 (LWP 2697)]
[New Thread 0x7fffcffff640 (LWP 2698)]
[Thread 0x7fffcf7fe640 (LWP 2697) exited]
[Thread 0x7fffcffff640 (LWP 2698) exited]
[New Thread 0x7fffcffff640 (LWP 2699)]
[New Thread 0x7fffcf7fe640 (LWP 2700)]

Thread 10 "calc_thread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcffff640 (LWP 2699)]
0x00007fffddf335a0 in ?? ()
(gdb) bt
#0  0x00007fffddf335a0 in  ()
#1  0x00007ffff110dd1e in __gmpz_realloc () at /usr/lib/libgmp.so.10
#2  0x00007ffff111021a in __gmpz_sub_ui () at /usr/lib/libgmp.so.10
#3  0x00007ffff114f17c in  () at /usr/lib/libgmp.so.10
#4  0x00007ffff114f41a in __gmp_randseed_ui () at /usr/lib/libgmp.so.10
#5  0x00005555556a7ea8 in Calculator::Calculator() (this=this@entry=0x7fffc800c390) at ../subprojects/libqalculate/libqalculate/Calculator.cc:168
#6  0x0000555555685e6d in new_calculator() () at ../subprojects/libqalculate/libqalculate/QalculateNasc.cc:15
#7  0x0000555555661662 in calculator_thread_thread_funcPython Exception <class 'ValueError'>: Variable 'static_fundamental_type_nodes' not found.
 (self=self@entry=) at com.github.parnold_x.nasc.p/src/Calculator.c:1169
#8  0x0000555555662ccf in _calculator_thread_thread_func_gthread_func (self=0x555556242950) at com.github.parnold_x.nasc.p/src/Calculator.c:3328
#9  0x00007ffff7dbfc20 in  () at /usr/lib/libglib-2.0.so.0
#10 0x00007ffff07f0662 in  () at /usr/lib/libc.so.6
#11 0x00007ffff0881d84 in clone () at /usr/lib/libc.so.6
```

**Comment by algent-al** [comment]
Fixed after updating some dependencies.
