### ISSUE TITLE
Sometimes it will crash on startup

### ISSUE THREAD

**Issue by Philip-Scott** [parnold-x/nasc#41]
```
[FATAL 09:54:10.439032] update_thread_construct: assertion 'file != NULL' failed

Thread 1 "nasc" received signal SIGSEGV, Segmentation fault.

#0 0x000000000041a84d in update_thread_ref ()
#1 0x000000000041aa8a in __lambda27_ ()
#2 0x000000000041ac8e in ___lambda27__gsource_func ()
#3 0x00007ffff590504a in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4 0x00007ffff59053f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5 0x00007ffff590549c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6 0x00007ffff75abd6d in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7 0x00007ffff7b6f390 in granite_application_run () from /usr/lib/x86_64-linux-gnu/libgranite.so.3
#8 0x000000000040e3f1 in nasc_nasc_app_main ()
#9 0x000000000040e42f in main ()```

**Comment by ksiddus** [comment]
Had the same problem - uninstall and reinstall seemed to have solved it!

**Comment by parnold-x** [comment]
Should be fixed
